# Generated by Django 4.2.2 on 2023-12-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterUser',
            new_name='RegisteredUser',
        ),
    ]
