# Generated by Django 4.2.2 on 2023-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0003_userprofile_delete_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('aboutus', 'About Us'), ('contactus', 'Contact Us'), ('cropintel', 'CropIntel'), ('agmachinex', 'AgMachineX'), ('agriclinic', 'AgriClinic'), ('fbi', 'FBI'), ('nutitracker', 'NutriTracker')], max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('backlinks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
