# Generated by Django 4.2.2 on 2023-12-23 07:41

import W2AI.models
import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0004_seocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10, null=True, unique=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('comments', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('type_of_image', models.CharField(choices=[('awards', 'Awards'), ('media coverages', 'Media Coverages'), ('approvals and licenses', 'Approvals and Licenses')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('blanket_n_value', models.FloatField()),
                ('blanket_p_value', models.FloatField()),
                ('blanket_k_value', models.FloatField()),
                ('stage_one_n_value', models.FloatField()),
                ('stage_one_p_value', models.FloatField()),
                ('stage_one_k_value', models.FloatField()),
                ('stage_two_n_value', models.FloatField()),
                ('stage_two_p_value', models.FloatField()),
                ('stage_two_k_value', models.FloatField()),
                ('stage_three_n_value', models.FloatField()),
                ('stage_three_p_value', models.FloatField()),
                ('stage_three_k_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_no', models.CharField(max_length=10)),
                ('crop_area', models.IntegerField(default=1)),
                ('available_of_str', models.BooleanField(default=True)),
                ('ph_value', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('n_value', models.FloatField(blank=True, null=True)),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('k_value', models.FloatField(blank=True, null=True)),
                ('nitrogen', models.FloatField(blank=True, choices=[('0.3', 'Low (30%)'), ('0.4', 'Medium(40%)'), ('0.5', 'High(50%)'), ('0.6', 'Very high(60%)')], null=True)),
                ('phosphorus', models.FloatField(blank=True, choices=[('0.3', 'Low (30%)'), ('0.4', 'Medium(40%)'), ('0.5', 'High(50%)'), ('0.6', 'Very high(60%)')], null=True)),
                ('potassium', models.FloatField(blank=True, choices=[('0.3', 'Low (30%)'), ('0.4', 'Medium(40%)'), ('0.5', 'High(50%)'), ('0.6', 'Very high(60%)')], null=True)),
                ('crop_stage', models.CharField(choices=[('Early Stage', 'Early Stage'), ('Growth Stage', 'Growth Stage'), ('Yield Stage', 'Yield Stage')], default=None, max_length=255, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='W2AI.crop')),
            ],
        ),
    ]
