# Generated by Django 4.2.2 on 2023-12-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0006_newfarmerpurchasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='advisor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
