# Generated by Django 4.2.2 on 2024-01-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0008_nutritracker_productpurchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgMachineSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_category', models.CharField(blank=True, choices=[('brush cutter', 'Brush Cutter'), ('power weeder', 'Power Weeder'), ('power tiller', 'Power Tiller'), ('water pump', 'Water Pump'), ('sprayer', 'Sprayer'), ('htp sprayer', 'HTP Sprayer'), ('earth auger', 'Earth Auger'), ('chainsaw', 'Chainsaw'), ('hedge trimmer', 'Hedge Trimmer'), ('chaff cutter', 'Chaff Cutter'), ('milking machine', 'Milking Machine'), ('lawn mower', 'Lawn Mower'), ('generator', 'Generator'), ('engine', 'Engine'), ('sprayer manual', 'Sprayer Manual'), ('milking machine manual', 'Milking Machine Manual'), ('coconut climber', 'Coconut Climber')], max_length=500, null=True)),
                ('crop', models.CharField(blank=True, max_length=500, null=True)),
                ('land_extent', models.CharField(blank=True, max_length=500, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('crop_stage', models.CharField(blank=True, max_length=200, null=True)),
                ('max_output', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_consumption', models.CharField(blank=True, max_length=500, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=500, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('portability', models.CharField(blank=True, max_length=200, null=True)),
                ('others', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgMachineXUserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('whatsapp_no', models.CharField(default='', max_length=255)),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(default='')),
                ('land_area', models.CharField(max_length=200)),
                ('crop_stage', models.CharField(choices=[('Early Stage', 'Early Stage'), ('Growth Stage', 'Growth Stage'), ('Yield Stage', 'Yield Stage')], max_length=255)),
                ('machinery_req', models.CharField(choices=[('brush cutter', 'Brush Cutter'), ('power weeder', 'Power Weeder'), ('power tiller', 'Power Tiller'), ('water pump', 'Water Pump'), ('sprayer', 'Sprayer'), ('htp sprayer', 'HTP Sprayer'), ('earth auger', 'Earth Auger'), ('chainsaw', 'Chainsaw'), ('hedge trimmer', 'Hedge Trimmer'), ('chaff cutter', 'Chaff Cutter'), ('milking machine', 'Milking Machine'), ('lawn mower', 'Lawn Mower'), ('generator', 'Generator'), ('engine', 'Engine'), ('sprayer manual', 'Sprayer Manual'), ('milking machine manual', 'Milking Machine Manual'), ('coconut climber', 'Coconut Climber')], max_length=500)),
                ('crop', models.CharField(max_length=500)),
                ('soil_type', models.CharField(choices=[('sandy soil', 'Sandy Soil'), ('clay soil', 'Clay Soil'), ('acidic soil', 'Acidic Soil'), ('alkaline soil', 'Alkaline Soil'), ('loamy soil', 'Loamy soil'), ('peaty soil', 'Peaty Soil'), ('chalky soil', 'Chalky Soil')], max_length=1000)),
                ('machine_available', models.CharField(choices=[('brush cutter', 'Brush Cutter'), ('power weeder', 'Power Weeder'), ('power tiller', 'Power Tiller'), ('water pump', 'Water Pump'), ('sprayer', 'Sprayer'), ('htp sprayer', 'HTP Sprayer'), ('earth auger', 'Earth Auger'), ('chainsaw', 'Chainsaw'), ('hedge trimmer', 'Hedge Trimmer'), ('chaff cutter', 'Chaff Cutter'), ('milking machine', 'Milking Machine'), ('lawn mower', 'Lawn Mower'), ('generator', 'Generator'), ('engine', 'Engine'), ('sprayer manual', 'Sprayer Manual'), ('milking machine manual', 'Milking Machine Manual'), ('coconut climber', 'Coconut Climber')], max_length=500)),
                ('budget', models.CharField(choices=[('between Rs. 20000 to Rs. 50000', 'Between Rs. 20000 to Rs. 50000'), ('between Rs. 50000 to Rs. 1,00,000', 'Between Rs. 50000 to Rs. 1,00,000'), ('between Rs. 1,00,000 to Rs. 1,50,000', 'Between Rs. 1,00,000 to Rs. 1,50,000'), ('between Rs. 1,50,000 to Rs. 2,00,000', 'Between Rs. 1,50,000 to Rs. 2,00,000'), ('between Rs. 2,00,000 to Rs. 2,50,000', 'Between Rs. 2, 00,000 to Rs. 2,50,000')], max_length=500)),
                ('purpose', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_density',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Bagalkot', 'Bagalkot'), ('Ballari (Bellary)', 'Ballari (Bellary)'), ('Belagavi (Belgaum)', 'Belagavi (Belgaum)'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikballapur', 'Chikballapur'), ('Chikkamagaluru (Chikmagalur)', 'Chikkamagaluru (Chikmagalur)'), ('Chitradurga', 'Chitradurga'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Hassan', 'Hassan'), ('Haveri', 'Haveri'), ('Kalaburagi (Gulbarga)', 'Kalaburagi (Gulbarga)'), ('Kodagu (Coorg)', 'Kodagu (Coorg)'), ('Kolar', 'Kolar'), ('Koppal', 'Koppal'), ('Mandya', 'Mandya'), ('Mysuru (Mysore)', 'Mysuru (Mysore)'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shivamogga (Shimoga)', 'Shivamogga (Shimoga)'), ('Tumakuru (Tumkur)', 'Tumakuru (Tumkur)'), ('Udupi', 'Udupi'), ('Uttara Kannada (Karwar)', 'Uttara Kannada (Karwar)'), ('Vijayapura (Bijapur)', 'Vijayapura (Bijapur)'), ('Yadgir', 'Yadgir')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plot_name1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plot_name2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plot_name3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plot_name4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plot_name5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taluk',
            field=models.CharField(blank=True, choices=[('Badami', 'Badami'), ('Bagalkot', 'Bagalkot'), ('Bilagi', 'Bilagi'), ('Hungund', 'Hungund'), ('Jamkhandi', 'Jamkhandi'), ('Mudhol', 'Mudhol'), ('Hosapete (Hospet)', 'Hosapete (Hospet)'), ('Sandur', 'Sandur'), ('Siruguppa', 'Siruguppa'), ('Kampli', 'Kampli'), ('Kudligi', 'Kudligi'), ('Athani', 'Athani'), ('Bailhongal', 'Bailhongal'), ('Chikodi', 'Chikodi'), ('Gokak', 'Gokak'), ('Hukkeri', 'Hukkeri'), ('Khanapur', 'Khanapur'), ('Ramdurg', 'Ramdurg'), ('Raybag', 'Raybag'), ('Saundatti-Yellamma', 'Saundatti-Yellamma'), ('Devanahalli', 'Devanahalli'), ('Doddaballapura', 'Doddaballapura'), ('Hosakote', 'Hosakote'), ('Nelamangala', 'Nelamangala'), ('Bangalore East', 'Bangalore East'), ('Bangalore North', 'Bangalore North'), ('Bangalore South', 'Bangalore South'), ('Bangalore West', 'Bangalore West'), ('Aurad', 'Aurad'), ('Basavakalyan', 'Basavakalyan'), ('Bhalki', 'Bhalki'), ('Homnabad', 'Homnabad'), ('Gundlupet', 'Gundlupet'), ('Kollegal', 'Kollegal'), ('Gauribidanur', 'Gauribidanur'), ('Bagepalli', 'Bagepalli'), ('Sidlaghatta', 'Sidlaghatta'), ('Kadur', 'Kadur'), ('Koppa', 'Koppa'), ('Mudigere', 'Mudigere'), ('Narasimharajapura', 'Narasimharajapura'), ('Sringeri', 'Sringeri'), ('Tarikere', 'Tarikere'), ('Challakere', 'Challakere'), ('Hiriyur', 'Hiriyur'), ('Holalkere', 'Holalkere'), ('Hosadurga', 'Hosadurga'), ('Molakalmuru', 'Molakalmuru'), ('Mangalore', 'Mangalore'), ('Bantwal', 'Bantwal'), ('Belthangady', 'Belthangady'), ('Puttur', 'Puttur'), ('Sullia', 'Sullia'), ('Harihar', 'Harihar'), ('Jagalur', 'Jagalur'), ('Harpanahalli', 'Harpanahalli'), ('Channagiri', 'Channagiri'), ('Hubballi (Hubli)', 'Hubballi (Hubli)'), ('Kalghatgi', 'Kalghatgi'), ('Kundgol', 'Kundgol'), ('Navalgund', 'Navalgund'), ('Mundargi', 'Mundargi'), ('Shirahatti', 'Shirahatti'), ('Nargund', 'Nargund'), ('Alur', 'Alur'), ('Arkalgud', 'Arkalgud'), ('Arsikere', 'Arsikere'), ('Belur', 'Belur'), ('Channarayapatna', 'Channarayapatna'), ('Holenarasipura', 'Holenarasipura'), ('Sakleshpur', 'Sakleshpur'), ('Byadagi', 'Byadagi'), ('Hangal', 'Hangal'), ('Hirekerur', 'Hirekerur'), ('Ranibennur', 'Ranibennur'), ('Savanur', 'Savanur'), ('Shiggaon', 'Shiggaon'), ('Afzalpur', 'Afzalpur'), ('Chincholi', 'Chincholi'), ('Chitapur', 'Chitapur'), ('Jevargi', 'Jevargi'), ('Sedam', 'Sedam'), ('Madikeri', 'Madikeri'), ('Virajpet', 'Virajpet'), ('Somwarpet', 'Somwarpet'), ('Bangarapet', 'Bangarapet'), ('Malur', 'Malur'), ('Mulbagal', 'Mulbagal'), ('Srinivaspur', 'Srinivaspur'), ('Gangawati', 'Gangawati'), ('Yelbarga', 'Yelbarga'), ('Kushtagi', 'Kushtagi'), ('Karatagi', 'Karatagi'), ('Kanakagiri', 'Kanakagiri'), ('Maddur', 'Maddur'), ('Malavalli', 'Malavalli'), ('Nagamangala', 'Nagamangala'), ('Pandavapura', 'Pandavapura'), ('Srirangapatna', 'Srirangapatna'), ('Heggadadevana Kote', 'Heggadadevana Kote'), ('Hunsur', 'Hunsur'), ('Krishnarajanagara', 'Krishnarajanagara'), ('Nanjangud', 'Nanjangud'), ('Piriyapatna', 'Piriyapatna'), ('T Narasipura (Tirumakudalu Narasipura)', 'T Narasipura (Tirumakudalu Narasipura)'), ('Sindhanur', 'Sindhanur'), ('Lingsugur', 'Lingsugur'), ('Manvi', 'Manvi'), ('Devadurga', 'Devadurga'), ('Maski', 'Maski'), ('Channapatna', 'Channapatna'), ('Kanakapura', 'Kanakapura'), ('Magadi', 'Magadi'), ('Bhadravathi', 'Bhadravathi'), ('Hosanagara', 'Hosanagara'), ('Sagara', 'Sagara'), ('Shikaripura', 'Shikaripura'), ('Sorab', 'Sorab'), ('Thirthahalli', 'Thirthahalli'), ('Chiknayakanhalli', 'Chiknayakanhalli'), ('Gubbi', 'Gubbi'), ('Kunigal', 'Kunigal'), ('Madhugiri', 'Madhugiri'), ('Pavagada', 'Pavagada'), ('Sira', 'Sira'), ('Tiptur', 'Tiptur'), ('Kundapura', 'Kundapura'), ('Karkala', 'Karkala'), ('Ankola', 'Ankola'), ('Bhatkal', 'Bhatkal'), ('Haliyal', 'Haliyal'), ('Karwar', 'Karwar'), ('Kumta', 'Kumta'), ('Mundgod', 'Mundgod'), ('Siddapur', 'Siddapur'), ('Sirsi', 'Sirsi'), ('Yellapur', 'Yellapur'), ('Basavana Bagevadi', 'Basavana Bagevadi'), ('Bijapur', 'Bijapur'), ('Indi', 'Indi'), ('Muddebihal', 'Muddebihal'), ('Sindgi', 'Sindgi'), ('Talikota', 'Talikota'), ('Shahapur', 'Shahapur'), ('Surpur', 'Surpur'), ('Shorapur', 'Shorapur')], max_length=500, null=True),
        ),
    ]
