# Generated by Django 4.2.2 on 2024-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0009_agmachinespecs_agmachinexuserinput_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='crops',
            field=models.CharField(blank=True, choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Pappya', 'Pappya')], max_length=255, null=True),
        ),
    ]
