# Generated by Django 4.2.2 on 2024-01-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0010_userprofile_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
