# Generated by Django 4.2.2 on 2024-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0011_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('whatsapp_no', models.CharField(max_length=10)),
                ('email_id', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productpurchased',
            name='product_code',
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='crop_density',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productpurchased',
            name='crop',
            field=models.CharField(blank=True, choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Pappya', 'Pappya')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productpurchased',
            name='product_name',
            field=models.CharField(blank=True, choices=[('Dr Soil Health', 'Dr Soil Health'), ('Dr Soil Health Areca Special', 'Dr Soil Health Areca Special'), ('Bio NPK', 'Bio NPK'), ('Bio Potash', 'Bio Potash'), ('Spirusan', 'Spirusan'), ('Amruth Banana Microbial Consortia', 'Amruth Banana Microbial Consortia'), ('Amruth Vegetable Microbial Consortia', 'Amruth Vegetable Microbial Consortia'), ('Amruth Sugarcane Microbial Consortia', 'Amruth Sugarcane Microbial Consortia'), ('Amruth Areca Microbial Consortia', 'Amruth Areca Microbial Consortia'), ('Humigreen', 'Humigreen'), ('Jeevarakshak', 'Jeevarakshak'), ('Humisan', 'Humisan'), ('Amino Gold', 'Amino Gold'), ('Indozyme', 'Indozyme'), ('Amruth Gold plus', 'Amruth Gold plus'), ('Bio-k Rich', 'Bio-k Rich'), ('Akshaya Areca Special', 'Akshaya Areca Special'), ('Arka Waste Decomposer', 'Arka Waste Decomposer'), ('Amezinc', 'Amezinc'), ('AmStrong', 'AmStrong'), ('Alzyme', 'Alzyme'), ('Micro Speed', 'Micro Speed'), ('Amruth Coffee Microbial Consortia', 'Amruth Coffee Microbial Consortia'), ('Altraset', 'Altraset'), ('Phos-Max', 'Phos-Max'), ('Phyton T', 'Phyton T'), ('MakeUp', 'MakeUp'), ('ProGibb', 'ProGibb'), ('Banana Micronutrient', 'Banana Micronutrient'), ('Mango Micronutrient', 'Mango Micronutrient'), ('Aquafert SOP', 'Aquafert SOP'), ('Gromor Spray 0-0-50', 'Gromor Spray 0-0-50'), ('GroMAG', 'GroMAG'), ('AcuMist Calcium', 'AcuMist Calcium'), ('Gromor Spray CN', 'Gromor Spray CN'), ('Gromor Sulphozinc', 'Gromor Sulphozinc'), ('Folibor', 'Folibor'), ('Tracel', 'Tracel'), ('Aquafert FPOV', 'Aquafert FPOV'), ('Gromor Spray 19:19:19', 'Gromor Spray 19:19:19'), ('Acuspray Sugarcane', 'Acuspray Sugarcane'), ('Power Plus', 'Power Plus'), ('Samrakshak', 'Samrakshak'), ('Alnym', 'Alnym'), ('Navarathna', 'Navarathna'), ('Alderm', 'Alderm'), ('Agri Nematode', 'Agri Nematode'), ('Almonas', 'Almonas'), ('Tatamida', 'Tatamida'), ('Sumipleo', 'Sumipleo'), ('Takumi', 'Takumi'), ('Reeva 5"%" EC', 'Reeva 5"%" EC'), ('Aaroosh', 'Aaroosh'), ('Blitox', 'Blitox'), ('Magnite', 'Magnite')], max_length=100, null=True),
        ),
    ]
