# Generated by Django 4.2.2 on 2024-01-16 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0013_newfarmerpurchasehistory_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='W2AI.nutritracker')),
            ],
        ),
    ]
