# Generated by Django 4.2.2 on 2024-01-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0014_existinguserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmachinespecs',
            name='others',
        ),
        migrations.AddField(
            model_name='agmachinespecs',
            name='drip_irrigation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
