# Generated by Django 4.2.2 on 2024-01-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0015_remove_agmachinespecs_others_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgMachineSpecs',
            new_name='AgMachineSpecifications',
        ),
    ]
