# Generated by Django 4.2.2 on 2024-01-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0016_rename_agmachinespecs_agmachinespecifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agmachinespecifications',
            options={'verbose_name': 'AgMachineX Specifications'},
        ),
    ]
