# Generated by Django 4.2.2 on 2024-01-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0018_alter_agmachinespecifications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agmachinexuserinput',
            options={'verbose_name': 'AgMachinex User Enquiries', 'verbose_name_plural': 'AgMachinex User Enquiries'},
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='budget',
            field=models.CharField(max_length=500),
        ),
    ]
