# Generated by Django 4.2.2 on 2024-01-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0019_alter_agmachinexuserinput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agmachinespecifications',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
