# Generated by Django 4.2.2 on 2024-01-17 06:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0020_alter_agmachinespecifications_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmachinespecifications',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
