# Generated by Django 4.2.2 on 2024-01-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0022_agrifbi_currentmonthreport_lastmonthreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrifbi',
            name='current_month',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.currentmonthreport'),
        ),
        migrations.AddField(
            model_name='agrifbi',
            name='last_month',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.lastmonthreport'),
        ),
        migrations.AddField(
            model_name='agrifbi',
            name='seasonal_month',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.seasonalreport'),
        ),
    ]
