# Generated by Django 4.2.2 on 2024-01-18 05:08

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0023_agrifbi_current_month_agrifbi_last_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrifbi',
            name='current_month',
        ),
        migrations.RemoveField(
            model_name='agrifbi',
            name='last_month',
        ),
        migrations.RemoveField(
            model_name='agrifbi',
            name='seasonal_month',
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='bull_bear_factors_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='events_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='farmer_advisor_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='news_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='notifications_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='price_outlook_kannada',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='currentmonthreport',
            name='summary_reviews_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastmonthreport',
            name='bull_bear_factors_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastmonthreport',
            name='crop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.agrifbi'),
        ),
        migrations.AddField(
            model_name='lastmonthreport',
            name='price_outlook_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lastmonthreport',
            name='user_feedback_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='bull_bear_factors_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='crop',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.agrifbi'),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='price_outlook_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='summary_reviews_kannada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='bull_bear_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='W2AI.agrifbi'),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='crop_trend',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='farmer_advisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='notifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='price_outlook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='currentmonthreport',
            name='summary_reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastmonthreport',
            name='price_outlook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lastmonthreport',
            name='user_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='bull_bear_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='price_outlook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='summary_reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
