# Generated by Django 4.2.2 on 2024-01-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0024_remove_agrifbi_current_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrifbi',
            options={'verbose_name': 'Way2ABI Agri FBI Crop Reports', 'verbose_name_plural': 'Way2ABI Agri FBI Crop Reports'},
        ),
    ]
