# Generated by Django 4.2.2 on 2024-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0027_agrifbi_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrifbi',
            name='crop',
            field=models.CharField(choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Pappya', 'Pappya')], max_length=500),
        ),
    ]
