# Generated by Django 4.2.2 on 2024-01-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0028_alter_agrifbi_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBIEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='W2AI.userprofile')),
            ],
            options={
                'verbose_name': 'W2ABI Agri FBI User Input',
                'verbose_name_plural': 'W2ABI Agri FBI User Input',
            },
        ),
    ]
