# Generated by Django 4.2.2 on 2024-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0029_fbienquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbienquiry',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='fbienquiry',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fbienquiry',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
