# Generated by Django 4.2.2 on 2024-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0030_remove_fbienquiry_user_profile_fbienquiry_phone_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropIntelKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Pappya', 'Pappya')], max_length=500)),
                ('market_prospects', models.TextField(max_length=1000)),
                ('yield_potential', models.TextField(max_length=1000)),
                ('area_suitability', models.TextField(max_length=1000)),
                ('soil_suitability', models.TextField(max_length=1000)),
                ('irrigation_req', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'CropIntel KnowledgeBase',
            },
        ),
    ]
