# Generated by Django 4.2.2 on 2024-01-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0033_alter_cropintelknowledge_options_cropintelinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropintelinput',
            name='user',
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='user_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
