# Generated by Django 4.2.2 on 2024-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0034_remove_cropintelinput_user_cropintelinput_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropintelinput',
            name='atmospheric_pressure',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='cloud',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='humidity',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='irrigation_technique',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='temperature',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='water_availability',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='weather',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='wind_condition',
            field=models.CharField(default='', max_length=500),
        ),
    ]
