# Generated by Django 4.2.2 on 2024-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0035_cropintelinput_atmospheric_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutriTrackerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crops', models.CharField(choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Pappya', 'Pappya')], max_length=500)),
                ('crop_stage', models.CharField(choices=[('Early Stage', 'Early Stage'), ('Yielding Stage', 'Yielding Stage'), ('Flowering', 'Flowering'), ('Growth Stage', 'Growth Stage'), ('Fruiting', 'Fruiting')], max_length=500)),
                ('crop_types', models.CharField(choices=[('Annual Crops', 'Annual Crops'), ('Perennial Crops', 'Perennial Crops'), ('Biannual Crops', 'Biannual Crops'), ('Biennial Crops', 'Biennial Crops')], max_length=500)),
                ('scheduling_period', models.CharField(max_length=500)),
            ],
        ),
    ]
