# Generated by Django 4.2.2 on 2024-01-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0036_nutritrackerschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('farm_size', models.IntegerField()),
                ('crop_details', models.TextField()),
                ('current_farm_tech', models.TextField()),
                ('challenges', models.TextField()),
                ('service_requirement', models.TextField()),
            ],
            options={
                'verbose_name': 'Value Added or Custom Services',
                'verbose_name_plural': 'Value Added or Custom Services',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('services_used', models.CharField(choices=[('CropIntel', 'CropIntel'), ('AgMachineX', 'AgMachineX'), ('Agri FBI', 'Agri FBI'), ('AgriClinic', 'AgriClinic'), ('NutriTracker', 'NutriTracker')], max_length=255)),
                ('service_effectiveness', models.TextField()),
                ('improvement_area', models.TextField()),
                ('feedback', models.TextField()),
            ],
            options={
                'verbose_name': 'User Feedback for W2AI Services',
                'verbose_name_plural': 'User Feedback for W2AI Services',
            },
        ),
        migrations.AlterModelOptions(
            name='nutritrackerschedule',
            options={'verbose_name': 'NT Scheduling Period Record', 'verbose_name_plural': 'NT Scheduling Period Record'},
        ),
    ]
