# Generated by Django 4.2.2 on 2024-01-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0037_addedservices_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='services_used',
            field=models.CharField(max_length=255),
        ),
    ]
