# Generated by Django 4.2.2 on 2024-01-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0038_alter_feedback_services_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='improvement_area',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='service_effectiveness',
        ),
    ]
