# Generated by Django 4.2.2 on 2024-03-27 09:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0040_feedback_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('text1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
