# Generated by Django 4.2.2 on 2024-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0044_alter_newfarmerpurchasehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmachinespecifications',
            name='drip_irrigation',
        ),
        migrations.RemoveField(
            model_name='agmachinespecifications',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='crop_density',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='plot_name1',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='plot_name2',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='plot_name3',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='plot_name4',
        ),
        migrations.RemoveField(
            model_name='agmachinexuserinput',
            name='plot_name5',
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('Short Term', 'Short Term'), ('Perennial', 'Perennial')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='irrigation_solution',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Flood', 'Flood'), ('Sprinkler', 'Sprinkler')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='irrigation_usage',
            field=models.CharField(blank=True, choices=[('Irrigation Only', 'Irrigation Only'), ('Fertigation Included', 'Fertion Included')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='labour_employed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agmachinespecifications',
            name='soil_condition',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='current_irrigation_method',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Flood', 'Flood'), ('Sprinkler', 'Sprinkler'), ('Others', 'Others')], default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='irrigation_req',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Sprinkler', 'Sprinkler'), ('For Fertigation', 'For Fertigation')], default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Flood', 'Flood'), ('Sprinkler', 'Sprinkler'), ('Others', 'Others')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='labours_employed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='other_current_irrigation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='soil_condition',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='water_availability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='water_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinespecifications',
            name='crop',
            field=models.CharField(blank=True, choices=[('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Avocado', 'Avocado'), ('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Carrot', 'Carrot'), ('Cashewnut', 'Cashewnut'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Chilli', 'Chilli'), ('Chrysanthemum', 'Chrysanthemum'), ('Citrus', 'Citrus'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Curry Leaves', 'Curry Leaves'), ('Custard Apple', 'Custard Apple'), ('Dragon Fruit', 'Dragon Fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Ginger', 'Ginger'), ('Grapes', 'Grapes'), ('Groundnut', 'Groundnut'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Maize', 'Maize'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pine apple'), ('Pomegranate', 'Pomegranate'), ('Potato', 'Potato'), ('Rambutan', 'Rambutan'), ('Rose', 'Rose'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Sugarcane', 'Sugarcane'), ('Tender Coconut', 'Tender Coconut'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Turmeric', 'Turmeric')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinespecifications',
            name='crop_stage',
            field=models.CharField(blank=True, choices=[('Early', 'Early'), ('Growth', 'Growth'), ('Yield', 'Yield')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinespecifications',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('Fuel', 'Fuel'), ('Battery', 'Battery')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinespecifications',
            name='quality',
            field=models.CharField(blank=True, choices=[('Economical', 'Economical'), ('Premium', 'Premium')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='crop_stage',
            field=models.CharField(blank=True, choices=[('Early Stage', 'Early Stage'), ('Growth Stage', 'Growth Stage'), ('Yield Stage', 'Yield Stage')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='land_area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='machine_available',
            field=models.CharField(blank=True, choices=[('Irrigation Systems', 'Irrigation Systems'), ('brush cutter', 'Brush Cutter'), ('power weeder', 'Power Weeder'), ('power tiller', 'Power Tiller'), ('water pump', 'Water Pump'), ('sprayer', 'Sprayer'), ('htp sprayer', 'HTP Sprayer'), ('earth auger', 'Earth Auger'), ('chainsaw', 'Chainsaw'), ('hedge trimmer', 'Hedge Trimmer'), ('chaff cutter', 'Chaff Cutter'), ('milking machine', 'Milking Machine'), ('lawn mower', 'Lawn Mower'), ('generator', 'Generator'), ('engine', 'Engine'), ('sprayer manual', 'Sprayer Manual'), ('milking machine manual', 'Milking Machine Manual'), ('coconut climber', 'Coconut Climber')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='machinery_req',
            field=models.CharField(choices=[('Irrigation Systems', 'Irrigation Systems'), ('brush cutter', 'Brush Cutter'), ('power weeder', 'Power Weeder'), ('power tiller', 'Power Tiller'), ('water pump', 'Water Pump'), ('sprayer', 'Sprayer'), ('htp sprayer', 'HTP Sprayer'), ('earth auger', 'Earth Auger'), ('chainsaw', 'Chainsaw'), ('hedge trimmer', 'Hedge Trimmer'), ('chaff cutter', 'Chaff Cutter'), ('milking machine', 'Milking Machine'), ('lawn mower', 'Lawn Mower'), ('generator', 'Generator'), ('engine', 'Engine'), ('sprayer manual', 'Sprayer Manual'), ('milking machine manual', 'Milking Machine Manual'), ('coconut climber', 'Coconut Climber')], max_length=500),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='taluk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
