# Generated by Django 4.2.2 on 2024-05-04 12:37

import cloudinary.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0045_remove_agmachinespecifications_drip_irrigation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropintelinput',
            name='irrigation_technique',
        ),
        migrations.RemoveField(
            model_name='cropintelinput',
            name='soil_test_report',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='area_suitability',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='irrigation_req',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='season_info',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='soil_suitability',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='spatial_distance',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='weather_info',
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='crop_grown',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='crop_varieties',
            field=models.CharField(blank=True, choices=[('NA-7', 'NA-7'), ('Krishna', 'Krishna'), ('Kanchana', 'Kanchana'), ('Chakiya', 'Chakiya'), ('Mangalore White Chali', 'Mangalore White Chali'), ('Shimoga', 'Shimoga'), ('Davanagere Api', 'Davanagere Api'), ('Chikkamagalore Saraku', 'Chikkamagalore Saraku'), ('North kanara rashi', 'North kanara rashi'), ('Hirehalli local', 'Hirehalli local'), ('Tumkur local', 'Tumkur local'), ('Mohith Nagar', 'Mohith Nagar'), ('Sirsi local', 'Sirsi local'), ('Tirthahalli Local', 'Tirthahalli Local'), ('Sagar Local', 'Sagar Local'), ('Sumangala', 'Sumangala'), ('Mangala', 'Mangala'), ('Hass', 'Hass'), ('Florida gold', 'Florida gold'), ('Green gold', 'Green gold'), ('Kaveri grand', 'Kaveri grand'), ('B N grand', 'B N grand'), ('B G S grand', 'B G S grand'), ('G9', 'G9'), ('Yellaki', 'Yellaki'), ('Nendran', 'Nendran'), ('Mysoreale', 'Mysoreale'), ('Kariyale', 'Kariyale'), ('Ambudiale', 'Ambudiale'), ('V-4', 'V-4'), ('V-7', 'V-7'), ('Bhaskara', 'Bhaskara'), ('Ullal-1', 'Ullal-1'), ('Ullal-5', 'Ullal-5'), ('Criollo', 'Criollo'), ('Trinitario', 'Trinitario'), ('Forastero', 'Forastero'), ('Tiptur', 'Tiptur'), ('Arasikere tall', 'Arasikere tall'), ('West coast tall', 'West coast tall'), ('Arabica', 'Arabica'), ('Sen kaampa', 'Sen kaampa'), ('Dharwad-1', 'Dharwad-1'), ('Dharwad-2', 'Dharwad-2'), ('Gamthi', 'Gamthi'), ('NMK-1 Golden', 'NMK-1 Golden'), ('White Dragon -1', 'White Dragon -1'), ('Jumbo red dragon -1', 'Jumbo red dragon -1'), ('Pink dragon', 'Pink dragon'), ('Rohith-1', 'Rohith-1'), ('Coimbature-2', 'Coimbature-2'), ('PKM-1', 'PKM-1'), (' PKM-2', 'PKM-2'), ('Mornthong', 'Mornthong'), ('Chanee', 'Chanee'), ('Kani', 'Kani'), ('Brown turkey', 'Brown turkey'), ('Puna Fig', 'Puna Fig'), ('Thompson seedless', 'Thompson seedless'), ('Sharad seedless', 'Sharad seedless'), ('Red globe', 'Red globe'), ('Dilkush', 'Dilkush'), ('Blanc du Bois', 'Blanc du Bois'), ('Sonaka seedless', 'Sonaka seedless'), ('Tas-e-ganesh', 'Tas-e-ganesh'), ('Allahabad safeda guava', 'Allahabad safeda guava'), ('Dimond seedless', 'Dimond seedless'), ('Thai white seedless', 'Thai white seedless'), ('Siddu variety', 'Siddu variety'), ('Khaja variety', 'Khaja variety'), ('Rudrakshi', 'Rudrakshi'), ('Mysuru mallige', 'Mysuru mallige'), ('Udupi mallige', 'Udupi mallige'), ('Konkan Amritha', 'Konkan Amritha'), ('Balaji', 'Balaji'), ('Kaggzi lemon', 'Kaggzi lemon'), ('Gol nemu', 'Gol nemu'), ('Macadamia integrifolia', 'Macadamia integrifolia'), ('Macadamia tetraphylla', 'Macadamia tetraphylla'), ('Forest spp', 'Forest spp'), ('Alphenso', 'Alphenso'), ('Malgova', 'Malgova'), ('Raspuri', 'Raspuri'), ('Bensha', 'Bensha'), ('Kesar', 'Kesar'), ('Mallika', 'Mallika'), ('Totapuri', 'Totapuri'), ('Neelam', 'Neelam'), ('Seashore mangosteen', 'Seashore mangosteen'), ('Sathgudi', 'Sathgudi'), ('Viswasree', 'Viswasree'), ('Keralashree', 'Keralashree'), ('Red lady', 'Red lady'), ('Panniyur -1', 'Panniyur -1'), ('Panniyur -2', 'Panniyur -2'), ('Panniyur -3', 'Panniyur -3'), ('Kari maligge sara', 'Kari maligge sara'), ('Queen', 'Queen'), ('Kew', 'Kew'), ('Bhagwa', 'Bhagwa'), ('Ganesh', 'Ganesh'), ('Mridula(Arakta)', 'Mridula(Arakta)'), ('Ruby', 'Ruby'), ('Arka Coorg Arun (Red colour)', 'Arka Coorg Arun (Red colour)'), ('Arka Coorg Peetabh (yellow colour)', 'Arka Coorg Peetabh (yellow colour)'), ('Indian Rosewood', 'Indian Rosewood'), ('Bahia Rosewood', 'Bahia Rosewood'), ('Cricket Ball', 'Cricket Ball'), ('Kalipatti', 'Kalipatti'), ('DHS-1', 'DHS-1'), ('DHS-2', 'DHS-2'), ('chowghat orange drawf', 'chowghat orange drawf'), ('Malayan Yellow Drawf', 'Malayan Yellow Drawf'), ('Ganga Bondum', 'Ganga Bondum')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='crop_yield',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='cultivation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='diseases',
            field=models.CharField(blank=True, choices=[('Leaf spot', 'Leaf spot'), ('Fruit rot/Koleroga', 'Fruit rot/Koleroga'), ('Bud rot', 'Bud rot'), ('Yellow leaf disease', 'Yellow leaf disease'), ('Infloresence die-back', 'Infloresence die-back'), ('Foot rot or Anabe roga', 'Foot rot or Anabe roga')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='inter_crops',
            field=models.CharField(blank=True, choices=[('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Arecanut', 'Arecanut'), ('Avocado', 'Avocado'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Cashewnut', 'Cashewnut'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Curry leaves', 'Curry leaves'), ('Custard apple', 'Custard apple'), ('Dragon fruit', 'Dragon fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Grapes', 'Grapes'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Rambutan', 'Rambutan'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Tender Coconut', 'Tender Coconut')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='land_prepration',
            field=models.CharField(blank=True, choices=[('Leveling', 'Leveling'), ('Clearing bushes', 'Clearing bushes'), ('Removing stones', 'Removing stones')], default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='no_of_plants',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='pests',
            field=models.CharField(blank=True, choices=[('Spindle bug', 'Spindle bug'), ('Root grub', 'Root grub'), ('Infloresence caterpillar', 'Infloresence caterpillar'), ('Cholam or white mites', 'Cholam or white mites')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='planting_date',
            field=models.CharField(blank=True, choices=[('Jan/2024', 'Jan/2024')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='planting_method',
            field=models.CharField(blank=True, choices=[('Intercrop', 'Intercrop'), ('Multicrop', 'Multicrop'), ('Monocrop', 'Monocrop')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='plot_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_average_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_health',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_ph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_poor_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='soil_rich_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='spacing',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='area_zone',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('North East Transition Zone', 'North East Transition Zone'), ('Northeastern Dry Zone', 'Northeastern Dry Zone'), ('Northern Dry Zone', 'Northern Dry Zone'), ('Central Dry Zone', 'Central Dry Zone'), ('Eastern Dry Zone', 'Eastern Dry Zone'), ('Southern Dry Zone', 'Southern Dry Zone'), ('Southern Transition Zone', 'Southern Transition Zone'), ('North Transition Zone', 'North Transition Zone'), ('Hill Zone', 'Hill Zone'), ('Coastal Zone', 'Coastal Zone'), ('Western (Malenadu) Zone', 'Western (malenadu) Zone')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='cover_crops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='crop_varieties',
            field=models.CharField(choices=[('NA-7', 'NA-7'), ('Krishna', 'Krishna'), ('Kanchana', 'Kanchana'), ('Chakiya', 'Chakiya'), ('Mangalore White Chali', 'Mangalore White Chali'), ('Shimoga', 'Shimoga'), ('Davanagere Api', 'Davanagere Api'), ('Chikkamagalore Saraku', 'Chikkamagalore Saraku'), ('North kanara rashi', 'North kanara rashi'), ('Hirehalli local', 'Hirehalli local'), ('Tumkur local', 'Tumkur local'), ('Mohith Nagar', 'Mohith Nagar'), ('Sirsi local', 'Sirsi local'), ('Tirthahalli Local', 'Tirthahalli Local'), ('Sagar Local', 'Sagar Local'), ('Sumangala', 'Sumangala'), ('Mangala', 'Mangala'), ('Hass', 'Hass'), ('Florida gold', 'Florida gold'), ('Green gold', 'Green gold'), ('Kaveri grand', 'Kaveri grand'), ('B N grand', 'B N grand'), ('B G S grand', 'B G S grand'), ('G9', 'G9'), ('Yellaki', 'Yellaki'), ('Nendran', 'Nendran'), ('Mysoreale', 'Mysoreale'), ('Kariyale', 'Kariyale'), ('Ambudiale', 'Ambudiale'), ('V-4', 'V-4'), ('V-7', 'V-7'), ('Bhaskara', 'Bhaskara'), ('Ullal-1', 'Ullal-1'), ('Ullal-5', 'Ullal-5'), ('Criollo', 'Criollo'), ('Trinitario', 'Trinitario'), ('Forastero', 'Forastero'), ('Tiptur', 'Tiptur'), ('Arasikere tall', 'Arasikere tall'), ('West coast tall', 'West coast tall'), ('Arabica', 'Arabica'), ('Sen kaampa', 'Sen kaampa'), ('Dharwad-1', 'Dharwad-1'), ('Dharwad-2', 'Dharwad-2'), ('Gamthi', 'Gamthi'), ('NMK-1 Golden', 'NMK-1 Golden'), ('White Dragon -1', 'White Dragon -1'), ('Jumbo red dragon -1', 'Jumbo red dragon -1'), ('Pink dragon', 'Pink dragon'), ('Rohith-1', 'Rohith-1'), ('Coimbature-2', 'Coimbature-2'), ('PKM-1', 'PKM-1'), (' PKM-2', 'PKM-2'), ('Mornthong', 'Mornthong'), ('Chanee', 'Chanee'), ('Kani', 'Kani'), ('Brown turkey', 'Brown turkey'), ('Puna Fig', 'Puna Fig'), ('Thompson seedless', 'Thompson seedless'), ('Sharad seedless', 'Sharad seedless'), ('Red globe', 'Red globe'), ('Dilkush', 'Dilkush'), ('Blanc du Bois', 'Blanc du Bois'), ('Sonaka seedless', 'Sonaka seedless'), ('Tas-e-ganesh', 'Tas-e-ganesh'), ('Allahabad safeda guava', 'Allahabad safeda guava'), ('Dimond seedless', 'Dimond seedless'), ('Thai white seedless', 'Thai white seedless'), ('Siddu variety', 'Siddu variety'), ('Khaja variety', 'Khaja variety'), ('Rudrakshi', 'Rudrakshi'), ('Mysuru mallige', 'Mysuru mallige'), ('Udupi mallige', 'Udupi mallige'), ('Konkan Amritha', 'Konkan Amritha'), ('Balaji', 'Balaji'), ('Kaggzi lemon', 'Kaggzi lemon'), ('Gol nemu', 'Gol nemu'), ('Macadamia integrifolia', 'Macadamia integrifolia'), ('Macadamia tetraphylla', 'Macadamia tetraphylla'), ('Forest spp', 'Forest spp'), ('Alphenso', 'Alphenso'), ('Malgova', 'Malgova'), ('Raspuri', 'Raspuri'), ('Bensha', 'Bensha'), ('Kesar', 'Kesar'), ('Mallika', 'Mallika'), ('Totapuri', 'Totapuri'), ('Neelam', 'Neelam'), ('Seashore mangosteen', 'Seashore mangosteen'), ('Sathgudi', 'Sathgudi'), ('Viswasree', 'Viswasree'), ('Keralashree', 'Keralashree'), ('Red lady', 'Red lady'), ('Panniyur -1', 'Panniyur -1'), ('Panniyur -2', 'Panniyur -2'), ('Panniyur -3', 'Panniyur -3'), ('Kari maligge sara', 'Kari maligge sara'), ('Queen', 'Queen'), ('Kew', 'Kew'), ('Bhagwa', 'Bhagwa'), ('Ganesh', 'Ganesh'), ('Mridula(Arakta)', 'Mridula(Arakta)'), ('Ruby', 'Ruby'), ('Arka Coorg Arun (Red colour)', 'Arka Coorg Arun (Red colour)'), ('Arka Coorg Peetabh (yellow colour)', 'Arka Coorg Peetabh (yellow colour)'), ('Indian Rosewood', 'Indian Rosewood'), ('Bahia Rosewood', 'Bahia Rosewood'), ('Cricket Ball', 'Cricket Ball'), ('Kalipatti', 'Kalipatti'), ('DHS-1', 'DHS-1'), ('DHS-2', 'DHS-2'), ('chowghat orange drawf', 'chowghat orange drawf'), ('Malayan Yellow Drawf', 'Malayan Yellow Drawf'), ('Ganga Bondum', 'Ganga Bondum')], default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='crop_variety_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='current_month_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='economical_yield_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='favorable_temp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='harvest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='high_density',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='historical_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='ideal_age_planting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='inter_crop_space',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='inter_crops',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='manure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='mean_sea_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='propagation_method',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Budding', 'Budding'), ('Softwood Grafting', 'Softwood Grafting'), ('Seeds', 'Seeds'), ('Cuttings', 'Cuttings'), ('Layering', 'Layering'), ('Grafting', 'Grafting'), ('Suckers', 'Suckers'), ('Tissue Culture', 'Tissue Culture'), ('Air Layering', 'Air Layering'), ('Epicotyl Grafting', 'Epicotyl Grafting'), ('Nuts', 'Nuts'), ('Stem Cuttings', 'Stem Cuttings'), ('Micropropagation', 'Micropropagation'), ('Blossoming', 'Blossoming'), ('Bud Grafting', 'Bud Grafting'), ('Shoot Cuttings', 'Shoot Cuttings')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='rainfall_req',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='recommend_space',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='relative_humidity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='seasonal_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='soil_pH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='soil_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sandy loam', 'Sandy loam'), ('Loamy Soil', 'Loamy Soil'), ('Black Soil', 'Black Soil'), ('Red Sandy Loam', 'Red Sandy Loam'), ('Lateritic Soil', 'Lateritic Soil'), ('Clay Loam Soil', 'Clay Loam Soil'), ('Red Lateritic Soil', 'Red Lateritic Soil'), ('Alluvial Clay', 'Alluvial Clay'), ('Coastal Alluvial Soil', 'Coastal Alluvial Soil'), ('Red Loamy Soil', 'Red Loamy Soil'), ('Mountainous Soil', 'Mountainous Soil'), ('Silt Loamy Soil', 'Silt Loamy Soil')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='water_req',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='wind_velocity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelinput',
            name='crop_stage',
            field=models.CharField(blank=True, choices=[('Young', 'Young'), ('Yielding', 'Yielding'), ('Old', 'Old')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelinput',
            name='water_availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='crop',
            field=models.CharField(choices=[('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Arecanut', 'Arecanut'), ('Avocado', 'Avocado'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Cashewnut', 'Cashewnut'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Curry leaves', 'Curry leaves'), ('Custard apple', 'Custard apple'), ('Dragon fruit', 'Dragon fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Grapes', 'Grapes'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Rambutan', 'Rambutan'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Tender Coconut', 'Tender Coconut')], max_length=500),
        ),
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='market_prospects',
            field=models.TextField(blank=True, choices=[('1. High Inflation (Positive Trending)', '1. High Inflation (Positive Trending)'), ('2. Elevated risk of price escalation (Positive Movement)', '2. Elevated risk of price escalation (Positive Movement)'), ('3. Price Convergence (High Spread)', '3. Price Convergence (High Spread)'), ('4. Potential risk of Decline(Negative Movement)', '4. Potential risk of Decline(Negative Movement'), ('5. Sharp Decline (Negative Trending)', '5. Sharp Decline (Negative Trending)')], null=True),
        ),
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='yield_potential',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
