# Generated by Django 4.2.2 on 2024-05-04 12:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0047_actualsales_fundrequirement_marketplannerstrategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACProductNPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(blank=True, choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('chili', 'chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], max_length=500, null=True)),
                ('category', models.CharField(choices=[('Organic Fertilizer', 'Organic Fertilizer'), ('Inorganic Fertilizer', 'Inorganic Fertilizer')], max_length=500)),
                ('sub_categories', models.CharField(choices=[('Nano Inforganic Fertilizer', 'Nano Inforganic Fertilizer'), ('Water Soluble Inorganic Fertilizer', 'Water Soluble Inorganic Fertilizer'), ('Complex Inorganic Fertilizer', 'Complex Inorganic Fertilizer'), ('Bulk Organic Fertilizer', 'Bulk Organic Fertilizer')], max_length=500)),
                ('product_name', models.CharField(max_length=500)),
                ('quantity_product', models.FloatField(default='')),
                ('product_link', models.CharField(default='', max_length=1000)),
                ('product_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('nitrogen', models.FloatField(blank=True, default=0.0, null=True)),
                ('phosphorus', models.FloatField(blank=True, default=0.0, null=True)),
                ('potassium', models.FloatField(blank=True, default=0.0, null=True)),
                ('sulphur', models.FloatField(blank=True, default=0.0, null=True)),
                ('calcium', models.FloatField(blank=True, default=0.0, null=True)),
                ('boron', models.FloatField(blank=True, default=0.0, null=True)),
                ('magnesium', models.FloatField(blank=True, default=0.0, null=True)),
                ('zinc', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('taluk', models.CharField(blank=True, max_length=255, null=True)),
                ('crop', models.CharField(choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('chili', 'chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], max_length=255)),
                ('disease_image', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
