# Generated by Django 4.2.2 on 2024-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0048_acproductnpk_diseaserecognition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomRecognitionKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('chili', 'chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], max_length=255)),
                ('disease', models.CharField(blank=True, max_length=500, null=True)),
                ('deficiencies', models.CharField(blank=True, max_length=500, null=True)),
                ('pests', models.CharField(blank=True, max_length=500, null=True)),
                ('symptoms', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
