# Generated by Django 4.2.2 on 2024-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0049_symptomrecognitionknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomsRecognitionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('whatsapp_no', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(default='', max_length=500)),
                ('district', models.CharField(blank=True, max_length=500, null=True)),
                ('taluk', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('crop', models.CharField(choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('chili', 'chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], max_length=255)),
                ('keywords', models.CharField(max_length=255)),
            ],
        ),
    ]
