# Generated by Django 4.2.2 on 2024-05-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0050_symptomsrecognitioninput'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notification_date', models.DateField()),
                ('fertilizers', models.CharField(max_length=500)),
                ('crop', models.CharField(max_length=500)),
                ('message', models.TextField()),
            ],
        ),
    ]
