# Generated by Django 4.2.2 on 2024-05-08 08:30

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0051_notificationrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atscontactproductinfo',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='atsseller',
            name='seller_product_images',
        ),
        migrations.CreateModel(
            name='ATSSellerProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_product_images', cloudinary.models.CloudinaryField(max_length=255)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='W2AI.atsseller')),
            ],
        ),
        migrations.CreateModel(
            name='ATSContactProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', cloudinary.models.CloudinaryField(default='', max_length=255)),
                ('seller', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='W2AI.atscontactinfo')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='W2AI.atscontactproductinfo')),
            ],
            options={
                'verbose_name': 'z5. Enter ATM Supplier Product Images',
                'verbose_name_plural': 'z5. Enter ATM Supplier Product Images',
            },
        ),
    ]
