# Generated by Django 4.2.2 on 2024-05-14 09:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0052_remove_atscontactproductinfo_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atscontactinfo',
            name='contact_company_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='atscontactinfo',
            name='contact_company_logo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
        ),
    ]
