# Generated by Django 4.2.2 on 2024-05-15 09:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0053_atscontactinfo_contact_company_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_title', models.CharField(max_length=500)),
                ('ppt', cloudinary.models.CloudinaryField(max_length=255)),
                ('alt', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'z6. Enter ATM Roadmap Details',
                'verbose_name_plural': 'z6. Enter ATM Roadmap Details',
            },
        ),
    ]
