# Generated by Django 4.2.2 on 2024-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0054_atsroadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsinfo',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
