# Generated by Django 4.2.2 on 2024-06-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0055_atsinfo_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='services_used',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='suggestions',
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_used', models.CharField(blank=True, choices=[('CropIntel', 'CropIntel'), ('AgMachineX', 'AgMachineX'), ('Agri FBI', 'Agri FBI'), ('AgriClinic', 'AgriClinic'), ('NutriTracker', 'NutriTracker')], default='', max_length=255, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, default='', null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(5, '★★★★★'), (4, '★★★★'), (3, '★★★'), (2, '★★'), (1, '★')], default=0, null=True)),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='W2AI.feedback')),
            ],
        ),
    ]
