# Generated by Django 4.2.2 on 2024-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0056_remove_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicefeedback',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
