# Generated by Django 4.2.2 on 2024-06-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0057_feedback_date_servicefeedback_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.CharField(default='', max_length=500),
        ),
    ]
