# Generated by Django 4.2.2 on 2024-06-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0058_remove_contact_subject_contact_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
