# Generated by Django 4.2.2 on 2024-07-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0060_alter_acproductnpk_options_alter_actualsales_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroTextDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Englishdescription', models.TextField()),
                ('Kannadadescription', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Enter Kannada and English Description AGI',
                'verbose_name_plural': 'Enter Kannada and English Description AGI',
            },
        ),
    ]
