# Generated by Django 4.2.2 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0061_introtextdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_seen',
            field=models.BooleanField(null=True),
        ),
    ]
