# Generated by Django 4.2.2 on 2024-08-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0063_alter_cropintelinput_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecognition',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
