# Generated by Django 4.2.2 on 2024-08-06 10:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0064_diseaserecognition_predicted_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseaserecognition',
            old_name='predicted_class',
            new_name='predicted_class0',
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='disease_image1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='disease_image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='disease_image3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='disease_image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='finalpredicted_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='predicted_class1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='predicted_class2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='predicted_class3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diseaserecognition',
            name='predicted_class4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
