# Generated by Django 4.2.2 on 2024-08-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0065_rename_predicted_class_diseaserecognition_predicted_class0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('Time', models.DateTimeField(null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Number',
            },
        ),
    ]
