# Generated by Django 4.2.2 on 2024-08-19 09:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0066_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropintelknowledge',
            name='price_forecast',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone_district',
            field=models.CharField(blank=True, choices=[('Anantapur', 'Anantapur'), ('Bagalkot', 'Bagalkot'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Belgaum', 'Belgaum'), ('Bidar', 'Bidar'), ('Bijapur(Vijayapura)', 'Bijapur(Vijayapura)'), ('Bellary', 'Bellary'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikmagalur(East)', 'Chikmagalur(East)'), ('Chikmagalur(West)', 'Chikmagalur(West)'), ('Chittoor(Andhra Pradesh)', 'Chittoor(Andhra Pradesh)'), ('Chitradurga', 'Chitradurga'), ('Coorg(Madikeri)(Kodagu))', 'Coorg(Madikeri)(Kodagu))'), ('Dakshina Kannada(Mangalore)', 'Dakshina Kannada(Mangalore)'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Gadag', 'Gadag'), ('Gulbarga(Kalaburgi)', 'Gulbarga(Kalaburgi)'), ('Haveri', 'Haveri'), ('Hassan', 'Hassan'), ('Kasargod(Kerala)', 'Kasargod(Kerala)'), ('Kolar', 'Kolar'), ('Koppala', 'Koppala'), ('Krishangiri(Tamil Nadu)', 'Krishangiri(Tamil Nadu)'), ('Mysuru', 'Mysuru'), ('Mandya', 'Mandya'), ('Nilgiris(Tamil Nadu)', 'Nilgiris(Tamil Nadu)'), ('Raichur', 'Raichur'), ('Ramanagara', 'Ramanagara'), ('Shimoga', 'Shimoga'), ('Tumkur', 'Tumkur'), ('Udupi', 'Udupi'), ('Uttara Kannada(East)', 'Uttara Kannada(East)'), ('Uttara Kannada(West)', 'Uttara Kannada(West)'), ('Wayanad(Kerala)', 'Wayanad(Kerala)'), ('Yadgir', 'Yadgir')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='area_zone',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Plain-North Zone', 'Plain-North Zone'), ('Plain-South Zone', 'Plain-South Zone'), ('Coastal Zone', 'Coastal Zone'), ('Western (Malenadu) Zone', 'Western (Malenadu) Zone')], default='', max_length=255),
        ),
    ]
