# Generated by Django 4.2.2 on 2024-08-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0069_alter_userprofile_taluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropintelinput',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
