# Generated by Django 4.2.2 on 2024-08-23 08:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0070_cropintelinput_created_at_cropintelinput_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='crop_varieties',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='historical_report',
        ),
        migrations.RemoveField(
            model_name='cropintelknowledge',
            name='price_forecast',
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='selected_crop_varieties',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cropintelknowledge',
            name='selected_intercrops',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='inter_crops',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Acacia', 'Acacia'), ('Avocado', 'Avocado'), ('Banana', 'Banana'), ('Cardamom', 'Cardamom'), ('Cashew Nut', 'Cashew Nut'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Citrus', 'Citrus'), ('Drumstick', 'Drumstick'), ('Dwarf sapota', 'Dwarf sapota'), ('Fig', 'Fig'), ('Ginger', 'Ginger'), ('Guava', 'Guava'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogany', 'Mahogany'), ('Medium term crops', 'Medium term crops'), ('NA', 'NA'), ('Nutmeg', 'Nutmeg'), ('Other Fruits Crops', 'Other Fruits Crops'), ('Papaya', 'Papaya'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Rubber', 'Rubber'), ('Sandalwood', 'Sandalwood'), ('Teak', 'Teak')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plot',
            name='water_availability',
            field=models.CharField(blank=True, choices=[('Very Good Water Availability', 'Very Good Water Availability'), ('Good Water Availability', 'Good Water Availability'), ('Average Water Availability', 'Average Water Availability'), ('Limited Water Availability', 'Limited Water Availability'), ('Poor Water Availability', 'Poor Water Availability')], max_length=255, null=True),
        ),
    ]
