# Generated by Django 4.2.2 on 2024-08-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0071_remove_cropintelknowledge_crop_varieties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropintelknowledge',
            name='water_req',
            field=models.CharField(blank=True, choices=[('Very Good Water Availability', 'Very Good Water Availability'), ('Good Water Availability', 'Good Water Availability'), ('Average Water Availability', 'Average Water Availability'), ('Limited Water Availability', 'Limited Water Availability'), ('Poor Water Availability', 'Poor Water Availability')], max_length=255, null=True),
        ),
    ]
