# Generated by Django 4.2.2 on 2024-09-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0072_alter_cropintelknowledge_water_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropintelinput',
            name='crop_varieties',
            field=models.CharField(blank=True, choices=[('NA-7', 'NA-7'), ('NA-10', 'NA-10'), ('Chakaiya', 'Chakaiya'), ('Kanchan', 'Kanchan'), ('Fuerte', 'Fuerte'), ('Pinkerton', 'Pinkerton'), ('Hass & Reed', 'Hass & Reed'), ('ICRI 2', 'ICRI 2'), ('IISR Suvarna', 'IISR Suvarna'), ('Malabar', 'Malabar'), ('Mudigere-1', 'Mudigere-1'), ('V-4', 'V-4'), ('Bhaskara', 'Bhaskara'), ('Ullal-1', 'Ullal-1'), ('Ullal-5', 'Ullal-5'), ('Criollo', 'Criollo'), ('Trinitario', 'Trinitario'), ('Forastero', 'Forastero'), ('Chowghat GD', 'Chowghat GD'), ('Chowghat OD', 'Chowghat OD'), ('West CT', 'West CT'), ('Arabica', 'Robusta'), ('Local Landrace Variety', 'Local Landrace Variety'), ('White Dragon-1', 'White Dragon-1'), ('Red dragon-1', 'Red dragon-1'), ('PKM-1', 'PKM-1'), ('Bhagya', 'Bhagya'), ('Trichy-1', 'Trichy-1'), ('Seedless- Thomson', 'Seedless- Thomson'), ('Sharad & Sonaka', 'Sharad & Sonaka'), ('Red globe', 'Red globe'), ('Allahabad Safeda', 'Allahabad Safeda'), ('Varikka', 'Varikka'), ('Idukki Gold', 'Idukki Gold'), ('Muttom Varikka', 'Muttom Varikka'), ('Bangalore Purple', 'Bangalore Purple'), ('Guthi', 'Guthi'), ('Eureka', 'Eureka'), ('Lisbon', 'Lisbon'), ('Meyer', 'Meyer'), ('Macadamia Integrifolia', 'Macadamia Integrifolia'), ('Macadamia Tetraphylla', 'Macadamia Tetraphylla'), ('Forest spp', 'Forest spp'), ('Alphenso', 'Alphenso'), ('Raspuri', 'Raspuri'), ('Mallika', 'Mallika'), ('Totapuri', 'Totapuri'), ('Neelam', 'Neelam'), ('Viswasree', 'Viswasree'), ('Keralashree', 'Keralashree'), ('Dura', 'Dura'), ('Tenera', 'Tenera'), ('Pisifera', 'Pisifera'), ('Panniyur-1', 'Panniyur-1'), ('Subhakara', 'Subhakara'), ('Panniyur-2', 'Panniyur-2'), ('Aimpiriyan', 'Aimpiriyan'), ('Bhagwa', 'Bhagwa'), ('Ganesh', 'Ganesh'), ('Mridula', 'Mridula'), ('Ruby', 'Ruby'), ('Cricket Ball', 'Cricket Ball'), ('Kalipatti', 'Kalipatti'), ('DHS-1', 'DHS-1'), ('DHS-2', 'DHS-2'), ('Indian Teak wood', 'Indian Teak wood')], max_length=255, null=True),
        ),
    ]
