# Generated by Django 4.2.2 on 2024-09-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0073_alter_cropintelinput_crop_varieties'),
    ]

    operations = [
        migrations.AddField(
            model_name='agmachinespecifications',
            name='vegetation_type',
            field=models.CharField(blank=True, choices=[('Grass & Weeds', 'Grass & Weeds'), ('Woody Vegetation', 'Woody Vegetation')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='vegetation_type',
            field=models.CharField(blank=True, choices=[('Grass & Weeds', 'Grass & Weeds'), ('Woody Vegetation', 'Woody Vegetation')], max_length=500, null=True),
        ),
    ]
