# Generated by Django 5.1.6 on 2025-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0075_seocontent_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
