# Generated by Django 5.1.6 on 2025-02-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0076_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Number',
        ),
        migrations.AlterField(
            model_name='advisor',
            name='crop',
            field=models.CharField(choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('chili', 'chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
