# Generated by Django 5.1.6 on 2025-02-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0078_remove_advisor_available_of_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='crop_grown',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='plot_name',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_average_nutrients',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_condition',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_health',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_ph',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_poor_nutrients',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='soil_rich_nutrients',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='water_availability',
        ),
        migrations.RemoveField(
            model_name='newfarmerpurchasehistory',
            name='water_source',
        ),
    ]
