# Generated by Django 5.1.6 on 2025-02-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0079_remove_newfarmerpurchasehistory_crop_grown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='crop_grown',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='plot_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_average_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_health',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_ph',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_poor_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='soil_rich_nutrients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='water_availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newfarmerpurchasehistory',
            name='water_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
