# Generated by Django 5.1.6 on 2025-02-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0080_newfarmerpurchasehistory_crop_grown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atscontactinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='atscontactproductinfo',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='atscontactproductimages',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='atscontactproductimages',
            name='seller_product',
        ),
        migrations.DeleteModel(
            name='ATSIntro',
        ),
        migrations.DeleteModel(
            name='ATSRoadmap',
        ),
        migrations.RemoveField(
            model_name='atssellerproductimage',
            name='seller',
        ),
        migrations.DeleteModel(
            name='ATSInfo',
        ),
        migrations.DeleteModel(
            name='ATSContactInfo',
        ),
        migrations.DeleteModel(
            name='ATSContactProductImages',
        ),
        migrations.DeleteModel(
            name='ATSContactProductInfo',
        ),
        migrations.DeleteModel(
            name='ATSSeller',
        ),
        migrations.DeleteModel(
            name='ATSSellerProductImage',
        ),
    ]
