# Generated by Django 5.1.6 on 2025-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0081_remove_atscontactinfo_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntfertilizerpurchase',
            name='new_user_info',
        ),
        migrations.DeleteModel(
            name='NotificationRecord',
        ),
        migrations.DeleteModel(
            name='NutriTrackerSchedule',
        ),
        migrations.RemoveField(
            model_name='productpurchased',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='nutritracker',
            options={},
        ),
        migrations.RenameField(
            model_name='nutritracker',
            old_name='micro_nutrients',
            new_name='crop_fertilizer_applied',
        ),
        migrations.RemoveField(
            model_name='existinguserprofile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='district',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='nutrients_freq',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='organic_carbon',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='other_irrigation',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='phosphorous',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='planting_month',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='secondary_nutrients',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='state',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='taluk',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='village',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='whatsapp_no',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='zone',
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='crop_grown',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='crop_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='fertilizer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='fertilizer_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='fertilizer_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='fertilizer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='micronutrients_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='nitrogen_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='nutrient_application_times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='nutrient_deficiency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='organic_carbon_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='phosphorous_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='plot_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='potassium_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='secondary_nutrients_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_avg_nutrients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_health',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_poor_nutrients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_rich_nutrients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='sowing_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='water_availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='water_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='crop_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='harvesting_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='irrigation_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NewFarmerPurchaseHistory',
        ),
        migrations.DeleteModel(
            name='NTFertilizerPurchase',
        ),
        migrations.DeleteModel(
            name='ProductPurchased',
        ),
    ]
