# Generated by Django 5.1.6 on 2025-02-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0082_remove_ntfertilizerpurchase_new_user_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritracker',
            options={'verbose_name': 'NutriTracker Form', 'verbose_name_plural': 'NutriTracker Forms'},
        ),
    ]
