# Generated by Django 5.1.6 on 2025-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0083_alter_nutritracker_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_grown', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('crop_density', models.IntegerField(blank=True, null=True)),
                ('soil_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_health', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_ph', models.FloatField(blank=True, null=True)),
                ('water_source', models.CharField(blank=True, max_length=100, null=True)),
                ('water_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('soil_rich_nutrients', models.TextField(blank=True, null=True)),
                ('soil_avg_nutrients', models.TextField(blank=True, null=True)),
                ('soil_poor_nutrients', models.TextField(blank=True, null=True)),
                ('sowing_month', models.CharField(blank=True, max_length=50, null=True)),
                ('harvesting_month', models.CharField(blank=True, max_length=50, null=True)),
                ('irrigation_method', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrient_application_times', models.IntegerField(blank=True, null=True)),
                ('nitrogen_value', models.FloatField(blank=True, null=True)),
                ('potassium_value', models.FloatField(blank=True, null=True)),
                ('phosphorous_value', models.FloatField(blank=True, null=True)),
                ('secondary_nutrients_value', models.FloatField(blank=True, null=True)),
                ('micronutrients_value', models.FloatField(blank=True, null=True)),
                ('organic_carbon_value', models.FloatField(blank=True, null=True)),
                ('crop_fertilizer_applied', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nutrient_deficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_quantity', models.FloatField(blank=True, null=True)),
                ('fertilizer_purchase_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agri FBI Form',
                'verbose_name_plural': 'Agri FBI Forms',
            },
        ),
    ]
