# Generated by Django 5.1.6 on 2025-02-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0084_fbi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbi',
            old_name='crop_grown',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='fbi',
            old_name='crop_stage',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fbi',
            old_name='fertilizer_name',
            new_name='taluk',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='crop_density',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='crop_fertilizer_applied',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='fertilizer_purchase_date',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='fertilizer_quantity',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='fertilizer_type',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='harvesting_month',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='irrigation_method',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='manufacturer_name',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='micronutrients_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='nitrogen_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='nutrient_application_times',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='nutrient_deficiency',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='organic_carbon_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='phosphorous_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='plot_name',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='potassium_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='secondary_nutrients_value',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_avg_nutrients',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_condition',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_health',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_ph',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_poor_nutrients',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='soil_rich_nutrients',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='sowing_month',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='water_availability',
        ),
        migrations.RemoveField(
            model_name='fbi',
            name='water_source',
        ),
        migrations.AddField(
            model_name='fbi',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fbi',
            name='land_extent',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fbi',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Seller', 'Seller (Farmer)'), ('Buyer', 'Buyer')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fbi',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CropDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('Paddy', 'Paddy'), ('Wheat', 'Wheat'), ('Maize', 'Maize'), ('Sugarcane', 'Sugarcane'), ('Cotton', 'Cotton'), ('Groundnut', 'Groundnut'), ('Tomato', 'Tomato'), ('Potato', 'Potato'), ('Onion', 'Onion'), ('Chilli', 'Chilli')], max_length=50)),
                ('crop_quantity', models.FloatField(help_text='Quantity in Quintal')),
                ('crop_variety', models.CharField(max_length=100)),
                ('fbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_details', to='W2AI.fbi')),
            ],
        ),
    ]
