# Generated by Django 5.1.6 on 2025-02-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0085_rename_crop_grown_fbi_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritracker',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='extent_of_land',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
