# Generated by Django 5.1.6 on 2025-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0086_nutritracker_address_nutritracker_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritracker',
            name='soil_avg_nutrients',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='soil_poor_nutrients',
        ),
        migrations.RemoveField(
            model_name='nutritracker',
            name='soil_rich_nutrients',
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='crop_fertilizer_applied',
            field=models.CharField(blank=True, choices=[('', '-- Select a Crop --'), ('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Avocado', 'Avocado'), ('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Carrot', 'Carrot'), ('Cashewnut', 'Cashewnut'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Chilli', 'Chilli'), ('Chrysanthemum', 'Chrysanthemum'), ('Citrus', 'Citrus'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Curry Leaves', 'Curry Leaves'), ('Custard Apple', 'Custard Apple'), ('Dragon Fruit', 'Dragon Fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Ginger', 'Ginger'), ('Grapes', 'Grapes'), ('Groundnut', 'Groundnut'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Maize', 'Maize'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Potato', 'Potato'), ('Rambutan', 'Rambutan'), ('Rose', 'Rose'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Sugarcane', 'Sugarcane'), ('Tender Coconut', 'Tender Coconut'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Turmeric', 'Turmeric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='crop_grown',
            field=models.CharField(blank=True, choices=[('', '-- Select a Crop --'), ('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Avocado', 'Avocado'), ('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Carrot', 'Carrot'), ('Cashewnut', 'Cashewnut'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Chilli', 'Chilli'), ('Chrysanthemum', 'Chrysanthemum'), ('Citrus', 'Citrus'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Curry Leaves', 'Curry Leaves'), ('Custard Apple', 'Custard Apple'), ('Dragon Fruit', 'Dragon Fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Ginger', 'Ginger'), ('Grapes', 'Grapes'), ('Groundnut', 'Groundnut'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Maize', 'Maize'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Potato', 'Potato'), ('Rambutan', 'Rambutan'), ('Rose', 'Rose'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Sugarcane', 'Sugarcane'), ('Tender Coconut', 'Tender Coconut'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Turmeric', 'Turmeric')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='crop_stage',
            field=models.CharField(blank=True, choices=[('', '-- Select Crop Stage --'), ('Early Stage', 'Early Stage'), ('Vegetative Stage', 'Vegetative Stage'), ('Yielding Stage', 'Yielding Stage')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='fertilizer_type',
            field=models.CharField(blank=True, choices=[('', '-- Select Fertilizer Type --'), ('Organic Fertilizer', 'Organic Fertilizer'), ('Inorganic Fertilizer', 'Inorganic Fertilizer'), ('FYM', 'FYM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='harvesting_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='irrigation_method',
            field=models.CharField(blank=True, choices=[('', '-- Select Irrigation Method --'), ('Drip', 'Drip'), ('Flood', 'Flood'), ('Sprinkler', 'Sprinkler'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='nutrient_deficiency',
            field=models.CharField(blank=True, choices=[('', '-- Select Nutrient --'), ('Organic Matter', 'Organic Matter'), ('Nitrogen (N)', 'Nitrogen (N)'), ('Phosphorus (P)', 'Phosphorus (P)'), ('Potassium (K)', 'Potassium (K)'), ('Calcium (Ca)', 'Calcium (Ca)'), ('Magnesium (Mg)', 'Magnesium (Mg)'), ('Sulphur (S)', 'Sulphur (S)'), ('Iron (Fe)', 'Iron (Fe)'), ('Manganese (Mn)', 'Manganese (Mn)'), ('Zinc (Zn)', 'Zinc (Zn)'), ('Copper (Cu)', 'Copper (Cu)'), ('Boron (B)', 'Boron (B)'), ('Molybdenum (Mo)', 'Molybdenum (Mo)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='soil_condition',
            field=models.CharField(blank=True, choices=[('', '-- Select Soil Condition --'), ('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='soil_health',
            field=models.CharField(blank=True, choices=[('', '-- Select Soil Health --'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='sowing_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='water_availability',
            field=models.CharField(blank=True, choices=[('', '-- Select Water Availability --'), ('Very Good Water Availability', 'Very Good Water Availability'), ('Good Water Availability', 'Good Water Availability'), ('Average Water Availability', 'Average Water Availability'), ('Limited Water Availability', 'Limited Water Availability'), ('Poor Water Availability', 'Poor Water Availability')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritracker',
            name='water_source',
            field=models.CharField(blank=True, choices=[('', '-- Select Water Source --'), ('Rain Fed', 'Rain Fed'), ('Borewell', 'Borewell'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
