# Generated by Django 5.1.6 on 2025-02-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0087_remove_nutritracker_soil_avg_nutrients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritracker',
            name='soil_avg_nutrients',
            field=models.TextField(blank=True, choices=[('', '-- Select Nutrient --'), ('Organic Matter', 'Organic Matter'), ('Nitrogen (N)', 'Nitrogen (N)'), ('Phosphorus (P)', 'Phosphorus (P)'), ('Potassium (K)', 'Potassium (K)'), ('Calcium (Ca)', 'Calcium (Ca)'), ('Magnesium (Mg)', 'Magnesium (Mg)'), ('Sulphur (S)', 'Sulphur (S)'), ('Iron (Fe)', 'Iron (Fe)'), ('Manganese (Mn)', 'Manganese (Mn)'), ('Zinc (Zn)', 'Zinc (Zn)'), ('Copper (Cu)', 'Copper (Cu)'), ('Boron (B)', 'Boron (B)'), ('Molybdenum (Mo)', 'Molybdenum (Mo)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_poor_nutrients',
            field=models.TextField(blank=True, choices=[('', '-- Select Nutrient --'), ('Organic Matter', 'Organic Matter'), ('Nitrogen (N)', 'Nitrogen (N)'), ('Phosphorus (P)', 'Phosphorus (P)'), ('Potassium (K)', 'Potassium (K)'), ('Calcium (Ca)', 'Calcium (Ca)'), ('Magnesium (Mg)', 'Magnesium (Mg)'), ('Sulphur (S)', 'Sulphur (S)'), ('Iron (Fe)', 'Iron (Fe)'), ('Manganese (Mn)', 'Manganese (Mn)'), ('Zinc (Zn)', 'Zinc (Zn)'), ('Copper (Cu)', 'Copper (Cu)'), ('Boron (B)', 'Boron (B)'), ('Molybdenum (Mo)', 'Molybdenum (Mo)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nutritracker',
            name='soil_rich_nutrients',
            field=models.TextField(blank=True, choices=[('', '-- Select Nutrient --'), ('Organic Matter', 'Organic Matter'), ('Nitrogen (N)', 'Nitrogen (N)'), ('Phosphorus (P)', 'Phosphorus (P)'), ('Potassium (K)', 'Potassium (K)'), ('Calcium (Ca)', 'Calcium (Ca)'), ('Magnesium (Mg)', 'Magnesium (Mg)'), ('Sulphur (S)', 'Sulphur (S)'), ('Iron (Fe)', 'Iron (Fe)'), ('Manganese (Mn)', 'Manganese (Mn)'), ('Zinc (Zn)', 'Zinc (Zn)'), ('Copper (Cu)', 'Copper (Cu)'), ('Boron (B)', 'Boron (B)'), ('Molybdenum (Mo)', 'Molybdenum (Mo)')], max_length=100, null=True),
        ),
    ]
