# Generated by Django 5.1.6 on 2025-02-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0088_nutritracker_soil_avg_nutrients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agmachinexuserinput',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='budget',
            field=models.CharField(blank=True, choices=[('Below than Rs. 10000', 'Below than Rs. 10000'), ('Between Rs. 10000 to Rs. 20000', 'Between Rs. 10000 to Rs. 20000'), ('Between Rs. 20000 to Rs. 50000', 'Between Rs. 20000 to Rs. 50000'), ('Between Rs. 50000 to Rs. 1,00,000', 'Between Rs. 50000 to Rs. 1,00,000'), ('Between Rs. 1,00,000 to Rs. 1,50,000', 'Between Rs. 1,00,000 to Rs. 1,50,000'), ('Between Rs. 1,50,000 to Rs. 2,00,000', 'Between Rs. 1,50,000 to Rs. 2,00,000'), ('Between Rs. 2,00,000 to Rs. 2,50,000', 'Between Rs. 2,00,000 to Rs. 2,50,000'), ('Above than Rs. 2,50,000', 'Above than Rs. 2,50,000')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='crop',
            field=models.CharField(blank=True, choices=[('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Banana', 'Banana'), ('Sugarcane', 'Sugarcane'), ('Coffee', 'Coffee'), ('Pepper', 'Pepper'), ('Papaya', 'Papaya')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='current_irrigation_method',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Flood', 'Flood'), ('Sprinkler', 'Sprinkler'), ('Others', 'Others')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='irrigation_req',
            field=models.CharField(blank=True, choices=[('Drip', 'Drip'), ('Sprinkler', 'Sprinkler'), ('For Fertigation', 'For Fertigation')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='machine_available',
            field=models.CharField(blank=True, choices=[('Irrigation Systems', 'Irrigation Systems'), ('Brush Cutter', 'Brush Cutter'), ('Power Weeder', 'Power Weeder'), ('Power Tiller', 'Power Tiller'), ('Water Pump', 'Water Pump'), ('Sprayer', 'Sprayer'), ('HTP Sprayer', 'HTP Sprayer'), ('Earth Auger', 'Earth Auger'), ('Chainsaw', 'Chainsaw'), ('Hedge Trimmer', 'Hedge Trimmer'), ('Chaff Cutter', 'Chaff Cutter'), ('Milking Machine', 'Milking Machine'), ('Lawn Mower', 'Lawn Mower'), ('Generator', 'Generator'), ('Engine', 'Engine'), ('Sprayer Manual', 'Sprayer Manual'), ('Milking Machine Manual', 'Milking Machine Manual'), ('Coconut Climber', 'Coconut Climber')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='machinery_req',
            field=models.CharField(blank=True, choices=[('Irrigation Systems', 'Irrigation Systems'), ('Brush Cutter', 'Brush Cutter'), ('Power Weeder', 'Power Weeder'), ('Power Tiller', 'Power Tiller'), ('Water Pump', 'Water Pump'), ('Sprayer', 'Sprayer'), ('HTP Sprayer', 'HTP Sprayer'), ('Earth Auger', 'Earth Auger'), ('Chainsaw', 'Chainsaw'), ('Hedge Trimmer', 'Hedge Trimmer'), ('Chaff Cutter', 'Chaff Cutter'), ('Milking Machine', 'Milking Machine'), ('Lawn Mower', 'Lawn Mower'), ('Generator', 'Generator'), ('Engine', 'Engine'), ('Sprayer Manual', 'Sprayer Manual'), ('Milking Machine Manual', 'Milking Machine Manual'), ('Coconut Climber', 'Coconut Climber')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='other_current_irrigation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='soil_condition',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard'), ('With Stone', 'With Stone')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agmachinexuserinput',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
