# Generated by Django 5.1.6 on 2025-02-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0089_agmachinexuserinput_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'verbose_name': 'AgriClinic: User Enquiry from Nutrient Deficiency Form', 'verbose_name_plural': 'AgriClinic: User Enquiry from Nutrient Deficiency Form'},
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='name',
        ),
        migrations.AddField(
            model_name='advisor',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='land_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='taluk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisor',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='advisor',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='crop',
            field=models.CharField(choices=[('Arecanut', 'Arecanut'), ('Banana', 'Banana'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Cotton', 'Cotton'), ('Maize', 'Maize'), ('Onion', 'Onion'), ('Paddy', 'Paddy'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pomegranate', 'Pomegranate'), ('Sugarcane', 'Sugarcane'), ('Tomato', 'Tomato'), ('Tur', 'Tur'), ('Potato', 'Potato'), ('Groundnut', 'Groundnut'), ('Chili', 'Chili'), ('Mango', 'Mango'), ('Rose', 'Rose'), ('Sapota', 'Sapota'), ('Ginger', 'Ginger'), ('Citrus (related fruits)', 'Citrus (related fruits)'), ('Chrysanthemum', 'Chrysanthemum'), ('Grapes', 'Grapes'), ('Cauliflower (Cole Crops)', 'Cauliflower (Cole Crops)'), ('Carrot', 'Carrot'), ('Turmeric', 'Turmeric')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
