# Generated by Django 5.1.6 on 2025-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('W2AI', '0090_alter_advisor_options_remove_advisor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropintelinput',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropintelinput',
            name='taluk',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cropintelinput',
            name='crop_grown',
            field=models.CharField(blank=True, choices=[('Amla', 'Amla'), ('Areca New', 'Areca New'), ('Arecanut', 'Arecanut'), ('Avocado', 'Avocado'), ('Banana', 'Banana'), ('Betelvine', 'Betelvine'), ('Cashewnut', 'Cashewnut'), ('Cocoa', 'Cocoa'), ('Coconut', 'Coconut'), ('Coffee', 'Coffee'), ('Curry leaves', 'Curry leaves'), ('Custard apple', 'Custard apple'), ('Dragon fruit', 'Dragon fruit'), ('Drumstick', 'Drumstick'), ('Durian', 'Durian'), ('Fig', 'Fig'), ('Grapes', 'Grapes'), ('Guava', 'Guava'), ('Jack Fruit', 'Jack Fruit'), ('Jasmin', 'Jasmin'), ('Kokum', 'Kokum'), ('Lime', 'Lime'), ('Macadamia', 'Macadamia'), ('Mahogani', 'Mahogani'), ('Mango', 'Mango'), ('Mangosteen', 'Mangosteen'), ('Mosambi', 'Mosambi'), ('Nutmeg', 'Nutmeg'), ('Papaya', 'Papaya'), ('Pepper', 'Pepper'), ('Pineapple', 'Pineapple'), ('Pomegranate', 'Pomegranate'), ('Rambutan', 'Rambutan'), ('Rosewood', 'Rosewood'), ('Sapota', 'Sapota'), ('Tender Coconut', 'Tender Coconut')], max_length=500, null=True),
        ),
    ]
