"""
Django settings for AgriIntel project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.api
import cloudinary.uploader

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_FARMER_DIRS = os.path.join(BASE_DIR, 'W2AI', 'templates')

# Security settings
SECRET_KEY = 'django-insecure-%tg&u^#fkfa#$)ysimk*g1(5!&ian9m7p!2g97dcr&eia%08px'
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'way2agriintel.com', 'www.way2agriintel.com']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'W2AI',
    'rest_framework',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgriIntel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_FARMER_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgriIntel.wsgi.application'

# Database settings
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'way2agriintel_db',
        'USER': 'agriintel',
        'PASSWORD': 'AVNS_qgDjmidFwvmuswaHsHt',
        'HOST': 'way2agribusiness-mysql-do-user-13941505-0.b.db.ondigitalocean.com',
        'PORT': 25060,
    }
}

# Authentication settings
LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = 'W2AI:login_url'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Localization settings
SITE_ID = 1
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static & media files settings
# URL to use when referring to static files
STATIC_URL = '/static/'

# Directories where Django will search for additional static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory where static files will be collected
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloudinary configuration
cloudinary.config(
    cloud_name='dm71xhdxd',
    api_key='855459367797631',
    api_secret='owidtLZTC0HQngNZBBo-wUzy7CU',
    secure=True,
)

# Project metadata
PROJECT_NAME = "AgriIntel"

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'agriclinic@way2agribusiness.com'
EMAIL_HOST_PASSWORD = 'Way2abi5*CLINIC'











# """
# Django settings for AgriIntel project.

# Generated by 'django-admin startproject' using Django 4.2.2.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """

# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# TEMPLATES_FARMER_DIRS=os.path.join(os.path.join(BASE_DIR,'W2AI'),'templates')

# import cloudinary
# import cloudinary.api
# import cloudinary.uploader
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-%tg&u^#fkfa#$)ysimk*g1(5!&ian9m7p!2g97dcr&eia%08px'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1','localhost','way2agriintel.com','www.way2agriintel.com']


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
# 	'django.contrib.sitemaps',
#     'django.contrib.staticfiles',
# 	'django.contrib.sites',
# 	'W2AI',
#     'rest_framework',
# 	'cloudinary',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'AgriIntel.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [TEMPLATES_FARMER_DIRS],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'AgriIntel.wsgi.application'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'way2agriintel_db',
#         'USER': 'agriintel',
#         'PASSWORD': 'AVNS_qgDjmidFwvmuswaHsHt',
#         'HOST': 'way2agribusiness-mysql-do-user-13941505-0.b.db.ondigitalocean.com',
#         'PORT': 25060,
#     }
# }

# # REST_FRAMEWORK = {
# #     'COERCE_DECIMAL_TO_STRING': False,
# #     'DEFAULT_AUTHENTICATION_CLASSES': (
# #         'rest_framework_simplejwt.authentication.JWTAuthentication',
# #     ),


# # }
# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# LOGIN_REDIRECT_URL = '/dashboard/'

# LOGIN_URL = 'W2AI:login_url'

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # this is you assets folder.
# # Internationalization
# # https://docs.djangoproject.com/en/4.2/topics/i18n/
# SITE_ID = 1
# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Kolkata'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# # STATIC_URL = 'static/'
# # STATIC_ROOT = os.path.join(os.path.join(BASE_DIR,'farmer'),'static')
# import os

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'W2AI/static'),  # If you have a static folder inside your project
# ]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # For collecting static files


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR,'media')
# DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# cloudinary.config( 
#   cloud_name = "dm71xhdxd", 
#   api_key = "855459367797631", 
#   api_secret = "owidtLZTC0HQngNZBBo-wUzy7CU" ,
#   secure=True,
# )

# PROJECT_NAME = "AgriIntel"

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtpout.secureserver.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'agriclinic@way2agribusiness.com'
# EMAIL_HOST_PASSWORD = 'Way2abi5*CLINIC'

